[[days]]
  name = "Понедельник"

  [[days.lessons]]
    time = "09:50-11:20"
    subject = "Основы дискретной математики (базовый уровень)"
    teacher = "Поляков Владимир Иванович"
    room = "2337"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Лекция"

  [[days.lessons]]
    time = "11:30-13:00"
    subject = "Основы дискретной математики (базовый уровень)"
    teacher = "Поляков Владимир Иванович"
    room = "2337"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Практика"

  [[days.lessons]]
    time = "13:30-15:00"
    subject = "Информатика"
    teacher = "Авксентьева Елена Юрьевна"
    room = "2305"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Лабораторная"

  [[days.lessons]]
    time = "15:30-17:00"
    subject = "Информатика"
    teacher = "Авксентьева Елена Юрьевна"
    room = "2305"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Лабораторная"

  [[days.lessons]]
    time = "17:10-18:40"
    subject = "Основы профессиональной деятельности"
    teacher = "Остапенко Ольга Денисовна"
    room = "1338"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Лабораторная"

  [[days.lessons]]
    time = "18:50-20:20"
    subject = "Основы профессиональной деятельности"
    teacher = "Остапенко Ольга Денисовна"
    room = "1338"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Лабораторная"

[[days]]
  name = "Суббота"

  [[days.lessons]]
    time = "13:30-15:00"
    subject = "Программирование"
    teacher = "Чупанов Аликылыч Аликбекович"
    room = "2305"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Лекция"

  [[days.lessons]]
    time = "15:30-17:00"
    subject = "Программирование"
    teacher = "Чупанов Аликылыч Аликбекович"
    room = "2305"
    building = "Кронверкский пр., д.49, лит.А"
    type = "Практика"

  [[days.lessons]]
    time = "18:50-20:20"
    subject = "История российской науки и техники"
    teacher = "Белоусов Александр Сергеевич"
    room = ""
    building = ""
    type = "Консультация"

  [[days.lessons]]
    time = "20:30-22:00"
    subject = "История российской науки и техники"
    teacher = "Белоусов Александр Сергеевич"
    room = ""
    building = ""
    type = "Консультация"
